// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApiTree: typeof import('./../src/components/Form/src/components/ApiTree.vue')['default'];
    DarkModeContainer: typeof import('./../src/components/common/DarkModeContainer.vue')['default'];
    DarkModeSwitch: typeof import('./../src/components/common/DarkModeSwitch.vue')['default'];
    FormAction: typeof import('./../src/components/Form/src/components/FormAction.vue')['default'];
    FormItem: typeof import('./../src/components/Form/src/components/FormItem.vue')['default'];
    HoverContainer: typeof import('./../src/components/common/HoverContainer.vue')['default'];
    NaiveProvider: typeof import('./../src/components/common/NaiveProvider.vue')['default'];
    NAvatar: typeof import('naive-ui')['NAvatar'];
    NBackTop: typeof import('naive-ui')['NBackTop'];
    NButton: typeof import('naive-ui')['NButton'];
    NColorPicker: typeof import('naive-ui')['NColorPicker'];
    NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
    NDataTable: typeof import('naive-ui')['NDataTable'];
    NDialogProvider: typeof import('naive-ui')['NDialogProvider'];
    NDivider: typeof import('naive-ui')['NDivider'];
    NDrawer: typeof import('naive-ui')['NDrawer'];
    NDrawerContent: typeof import('naive-ui')['NDrawerContent'];
    NDropdown: typeof import('naive-ui')['NDropdown'];
    NForm: typeof import('naive-ui')['NForm'];
    NFormItemGi: typeof import('naive-ui')['NFormItemGi'];
    NGradientText: typeof import('naive-ui')['NGradientText'];
    NGrid: typeof import('naive-ui')['NGrid'];
    NGridItem: typeof import('naive-ui')['NGridItem'];
    NIcon: typeof import('naive-ui')['NIcon'];
    NImage: typeof import('naive-ui')['NImage'];
    NInput: typeof import('naive-ui')['NInput'];
    NInputGroup: typeof import('naive-ui')['NInputGroup'];
    NInputNumber: typeof import('naive-ui')['NInputNumber'];
    NLayout: typeof import('naive-ui')['NLayout'];
    NLayoutContent: typeof import('naive-ui')['NLayoutContent'];
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader'];
    NLayoutSider: typeof import('naive-ui')['NLayoutSider'];
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider'];
    NMenu: typeof import('naive-ui')['NMenu'];
    NMessageProvider: typeof import('naive-ui')['NMessageProvider'];
    NModal: typeof import('naive-ui')['NModal'];
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider'];
    NPopconfirm: typeof import('naive-ui')['NPopconfirm'];
    NRadio: typeof import('naive-ui')['NRadio'];
    NRadioButton: typeof import('naive-ui')['NRadioButton'];
    NRadioGroup: typeof import('naive-ui')['NRadioGroup'];
    NScrollbar: typeof import('naive-ui')['NScrollbar'];
    NSelect: typeof import('naive-ui')['NSelect'];
    NSpace: typeof import('naive-ui')['NSpace'];
    NSwitch: typeof import('naive-ui')['NSwitch'];
    NTabPane: typeof import('naive-ui')['NTabPane'];
    NTabs: typeof import('naive-ui')['NTabs'];
    NTooltip: typeof import('naive-ui')['NTooltip'];
    NTree: typeof import('naive-ui')['NTree'];
    RadioGroup: typeof import('./../src/components/Form/src/components/RadioGroup.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Src: typeof import('./../src/components/Form/src/index.vue')['default'];
    Table: typeof import('./../src/components/Table/index.vue')['default'];
    TableAction: typeof import('./../src/components/Table/components/TableAction.vue')['default'];
    Toolbars: typeof import('./../src/components/Table/components/toolbars.vue')['default'];
  }
}
